Revert "Update dependency net.logstash.logback:logstash-logback-encoder to v8"
This reverts commit 30bc14317f23e254b42ac838c61e26017abe9bd2.
This fixes: NoClassDefFoundError: ch/qos/logback/access/common/spi/IAccessEvent